### ISSUE TITLE
Working with Homography in Net 4.5.2

### ISSUE THREAD

**Issue by nicolasroux** [nenoNaninu/HomographySharp#11]
Hello,

I would like to use your library, and I am working with VS 2015 in .Net 4.5.2.

I have tried to install the package but it requires a higher version of .Net.

However, it is written it should work with .Net Standard 2.0, but I can not find how.

Any help would be very appreciable,

Kinds Regards

**Comment by nenoNaninu** [comment]
.NET Framework 4.5.2 does not support .NET Standard 2.0. 
.NET Standard 2.0 is supported from .NET Framework 4.6.1. 

Please see the following documentation.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support
