### ISSUE TITLE
Compatible issue with .net472

### ISSUE THREAD

**Issue by balab2020** [nenoNaninu/HomographySharp#36]
When we use this package with .net 472 application. It fails in runtime. Can you please help us?

**Comment by nenoNaninu** [comment]
Can you give me the source code to reproduce the error?

**Comment by nenoNaninu** [comment]
In my test case, no runtime error occurs under net472 environment.

https://github.com/nenoNaninu/HomographySharpNet472

**Comment by balab2020** [comment]
Sorry it is my bad now .... it is not reproducible.

**Comment by balab2020** [comment]
Will reopen when I get the working code.

**Comment by balab2020** [comment]
This works with below settings only
`

<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.4.0" newVersion="4.1.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
`
